# Generated by Django 4.0.4 on 2023-10-15 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Project name')),
                ('creation_date', models.DateField(verbose_name='Creation date')),
                ('repo_url', models.CharField(max_length=150, verbose_name='Repository link')),
                ('files_folder', models.CharField(blank=True, max_length=150, null=True, verbose_name='Folder with .feature files')),
                ('smart_mode', models.BooleanField(default=False)),
                ('common_autotests_folder', models.CharField(blank=True, max_length=150, null=True, verbose_name='Common autotests folder')),
                ('git_access_key', models.CharField(blank=True, max_length=100, null=True, verbose_name='Git access token')),
                ('git_username', models.CharField(blank=True, default='user', max_length=100, null=True, verbose_name='Git username')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('1', 'PASSED'), ('2', 'FAILED'), ('3', 'UNDEFINED')], default='3', max_length=20, verbose_name='Test status')),
                ('text', models.TextField(blank=True, max_length=20000, null=True, verbose_name='Test comment')),
                ('test_name', models.CharField(max_length=200, verbose_name='Test name')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_label', models.CharField(max_length=100, verbose_name='Version label')),
                ('branch', models.CharField(default='main', max_length=100, verbose_name='Repoository branch')),
                ('commit_hash', models.CharField(blank=True, max_length=100, null=True, verbose_name='Commit hash')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Error message')),
                ('is_valid', models.BooleanField(default=True, verbose_name='Is version valid')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='api.project', verbose_name='Project')),
            ],
            options={
                'unique_together': {('project', 'version_label')},
            },
        ),
        migrations.CreateModel(
            name='TestStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(choices=[('1', 'Outcome'), ('2', 'Conjunction'), ('3', 'Unknown'), ('4', 'Action'), ('5', 'Context')], default='3', max_length=20, verbose_name='Step type')),
                ('text', models.TextField(blank=True, max_length=300, null=True, verbose_name='Test text')),
                ('has_auto_test', models.BooleanField(default=False)),
                ('project_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='api.projecttest', verbose_name='Feature step')),
            ],
        ),
        migrations.CreateModel(
            name='TestFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.FilePathField(match='.*?.feature', max_length=512, path='/home/vlad/Documents/projects/test_management_system/test-management-system/feature_files', recursive=True)),
                ('manually_created', models.BooleanField(default=False)),
                ('project_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_files', to='api.projectversion', verbose_name='Project Version')),
            ],
            options={
                'unique_together': {('project_version', 'file_path')},
            },
        ),
        migrations.AddField(
            model_name='projecttest',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='api.testfile', verbose_name='File'),
        ),
    ]
