# Generated by Django 4.0.4 on 2023-11-03 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_projecttest_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoTestStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(choices=[('1', 'Outcome'), ('2', 'Conjunction'), ('3', 'Unknown'), ('4', 'Action'), ('5', 'Context')], default='3', max_length=20, verbose_name='Step type')),
                ('text', models.TextField(blank=True, max_length=300, null=True, verbose_name='Test text')),
                ('project_file', models.ManyToManyField(related_name='auto_test_steps', to='api.testfile', verbose_name='Step in auto test files')),
            ],
        ),
    ]
