# Generated by Django 4.0.4 on 2023-11-09 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_project_file_autoteststep_project_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoteststep',
            name='text',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Test text'),
        ),
    ]
