# Generated by Django 4.0.4 on 2023-11-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_autoteststep_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='teststep',
            name='text_without_keyword',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Test text without keyword'),
        ),
    ]
