# Generated by Django 4.0.4 on 2023-11-09 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_teststep_text_without_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoteststep',
            name='is_common',
            field=models.BooleanField(default=False, verbose_name='Is this step common'),
        ),
    ]
