# Generated by Django 4.0.4 on 2023-11-19 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_autoteststep_is_common'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoteststep',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auto_test_steps', to='api.projectversion', verbose_name='Step in auto test files'),
        ),
    ]
