# Generated by Django 4.0.4 on 2023-11-19 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_autoteststep_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoteststep',
            name='autotests_folder_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Auto tests folder'),
        ),
    ]
