# Generated by Django 4.0.4 on 2023-12-06 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_autoteststep_autotests_folder_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='common_autotests_folder',
            new_name='common_autotests_folders',
        ),
    ]
